
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raul
 */
public class Nivel_2 extends javax.swing.JFrame {

    /**
     * Creates new form Nivel_2
     */
    public Nivel_2() {
        initComponents();
        ButtonGroupSexualidad.add(Masculino);
        ButtonGroupSexualidad.add(Femenino);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroupSexualidad = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        Confirmar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ConfirmarNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ConfirmarSexo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ConfirmarExpediente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ConfirmarArea = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConfirmarAlergias = new javax.swing.JEditorPane();
        jLabel8 = new javax.swing.JLabel();
        LabelCaidas1 = new javax.swing.JLabel();
        LabelCaidas2 = new javax.swing.JLabel();
        ConfirmarRiesgoUlsera = new javax.swing.JLabel();
        ConfirmarRiesgoCaida = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ConfirmarDia = new com.toedter.components.JSpinField();
        ConfirmarMes = new com.toedter.calendar.JMonthChooser();
        ConfirmarAño = new com.toedter.calendar.JYearChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        RegistrarPaciente = new javax.swing.JPanel();
        LabelTituloRegistro = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        NombrePasiente = new javax.swing.JTextField();
        LabelSexualidad = new javax.swing.JLabel();
        LabelFolio = new javax.swing.JLabel();
        NumExpediente = new javax.swing.JTextField();
        PanelNacimiento = new javax.swing.JPanel();
        FechaNacimiento = new com.toedter.calendar.JDateChooser();
        PanelIngreso = new javax.swing.JPanel();
        LabelArea = new javax.swing.JLabel();
        Area = new javax.swing.JComboBox<>();
        LabelTipoCama = new javax.swing.JLabel();
        TipoCama = new javax.swing.JComboBox<>();
        LabelNumCama = new javax.swing.JLabel();
        Cama = new javax.swing.JComboBox<>();
        LabelAlergias = new javax.swing.JLabel();
        LabelCaidas = new javax.swing.JLabel();
        RiesgoCaida = new javax.swing.JComboBox<>();
        RiesgoUlsera = new javax.swing.JComboBox<>();
        LabelUlsera = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alergias = new javax.swing.JEditorPane();
        Masculino = new javax.swing.JRadioButton();
        Femenino = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        jFrame1.setSize(new java.awt.Dimension(500, 430));

        Confirmar.setEnabled(false);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 131, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 131, Short.MAX_VALUE)
        );

        jLabel1.setText("Nombre");

        ConfirmarNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ConfirmarNombre.setText("jLabel2");

        jLabel3.setText("Sexo");

        ConfirmarSexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ConfirmarSexo.setText("jLabel4");

        jLabel5.setText("No.Expediente");

        ConfirmarExpediente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ConfirmarExpediente.setText("jLabel4");

        jLabel6.setText("Fecha deNacimiento");

        jLabel7.setText("Alergias");

        ConfirmarArea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ConfirmarArea.setText("jLabel4");

        ConfirmarAlergias.setEditable(false);
        ConfirmarAlergias.setEnabled(false);
        jScrollPane2.setViewportView(ConfirmarAlergias);

        jLabel8.setText("Area de Ingreso");

        LabelCaidas1.setText("Riesgo de Caida");

        LabelCaidas2.setText("Riesgo de Ulsera");

        ConfirmarRiesgoUlsera.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        ConfirmarRiesgoCaida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Aceptar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel10.setText("Confirmar Informacion");

        ConfirmarDia.setEnabled(false);

        ConfirmarMes.setEnabled(false);

        ConfirmarAño.setEnabled(false);

        org.jdesktop.layout.GroupLayout ConfirmarLayout = new org.jdesktop.layout.GroupLayout(Confirmar);
        Confirmar.setLayout(ConfirmarLayout);
        ConfirmarLayout.setHorizontalGroup(
            ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(ConfirmarLayout.createSequentialGroup()
                .addContainerGap()
                .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ConfirmarLayout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(ConfirmarLayout.createSequentialGroup()
                                .add(jLabel1)
                                .add(18, 18, 18)
                                .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(ConfirmarNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(ConfirmarLayout.createSequentialGroup()
                                        .add(ConfirmarSexo)
                                        .add(49, 49, 49)
                                        .add(jLabel5)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(ConfirmarExpediente))))
                            .add(jLabel3)
                            .add(ConfirmarLayout.createSequentialGroup()
                                .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel6)
                                    .add(jLabel8))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(ConfirmarArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jLabel7)
                    .add(ConfirmarLayout.createSequentialGroup()
                        .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ConfirmarLayout.createSequentialGroup()
                                .add(43, 43, 43)
                                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, ConfirmarDia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(ConfirmarLayout.createSequentialGroup()
                                .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(LabelCaidas2)
                                    .add(LabelCaidas1))
                                .add(18, 18, 18)
                                .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(ConfirmarRiesgoCaida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(ConfirmarRiesgoUlsera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(ConfirmarLayout.createSequentialGroup()
                                .add(24, 24, 24)
                                .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(ConfirmarLayout.createSequentialGroup()
                                .add(ConfirmarMes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(ConfirmarAño, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, ConfirmarLayout.createSequentialGroup()
                        .add(jLabel10)
                        .add(35, 35, 35)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ConfirmarLayout.setVerticalGroup(
            ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, ConfirmarLayout.createSequentialGroup()
                .add(jLabel10)
                .add(28, 28, 28)
                .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(ConfirmarLayout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel1)
                            .add(ConfirmarNombre))
                        .add(18, 18, 18)
                        .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(ConfirmarSexo)
                            .add(jLabel5)
                            .add(ConfirmarExpediente))
                        .add(18, 18, 18)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(ConfirmarDia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ConfirmarMes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ConfirmarAño, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(ConfirmarArea)
                            .add(jLabel8)))
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, ConfirmarLayout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(ConfirmarLayout.createSequentialGroup()
                                .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(ConfirmarRiesgoCaida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(ConfirmarLayout.createSequentialGroup()
                                        .add(15, 15, 15)
                                        .add(LabelCaidas1)))
                                .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(ConfirmarLayout.createSequentialGroup()
                                        .add(18, 18, 18)
                                        .add(ConfirmarRiesgoUlsera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(ConfirmarLayout.createSequentialGroup()
                                        .add(31, 31, 31)
                                        .add(LabelCaidas2))))
                            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(57, 57, 57))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, ConfirmarLayout.createSequentialGroup()
                        .add(ConfirmarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 500, Short.MAX_VALUE)
            .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jFrame1Layout.createSequentialGroup()
                    .add(0, 16, Short.MAX_VALUE)
                    .add(Confirmar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 17, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 430, Short.MAX_VALUE)
            .add(jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jFrame1Layout.createSequentialGroup()
                    .add(0, 20, Short.MAX_VALUE)
                    .add(Confirmar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(0, 21, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 10));

        jTabbedPane1.setAutoscrolls(true);

        RegistrarPaciente.setAutoscrolls(true);
        RegistrarPaciente.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                RegistrarPacienteComponentShown(evt);
            }
        });

        LabelTituloRegistro.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        LabelTituloRegistro.setText("Registro de Paciente");

        LabelNombre.setText("Nombre");

        LabelSexualidad.setText("Sexo:");

        LabelFolio.setText("Numero de expediente");

        NumExpediente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumExpedienteKeyTyped(evt);
            }
        });

        PanelNacimiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Nacimiento"));

        FechaNacimiento.setDateFormatString("yyyy-MM-d");

        org.jdesktop.layout.GroupLayout PanelNacimientoLayout = new org.jdesktop.layout.GroupLayout(PanelNacimiento);
        PanelNacimiento.setLayout(PanelNacimientoLayout);
        PanelNacimientoLayout.setHorizontalGroup(
            PanelNacimientoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(FechaNacimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 417, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        PanelNacimientoLayout.setVerticalGroup(
            PanelNacimientoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(FechaNacimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        PanelIngreso.setBorder(javax.swing.BorderFactory.createTitledBorder("Area de Ingreso"));

        LabelArea.setText("Area");

        LabelTipoCama.setText("Tipo de Cama");

        TipoCama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "General", "Asilada" }));

        LabelNumCama.setText("No Cama");

        Cama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));

        org.jdesktop.layout.GroupLayout PanelIngresoLayout = new org.jdesktop.layout.GroupLayout(PanelIngreso);
        PanelIngreso.setLayout(PanelIngresoLayout);
        PanelIngresoLayout.setHorizontalGroup(
            PanelIngresoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelIngresoLayout.createSequentialGroup()
                .addContainerGap()
                .add(LabelArea)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(Area, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(LabelTipoCama)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(TipoCama, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(41, 41, 41)
                .add(LabelNumCama)
                .add(18, 18, 18)
                .add(Cama, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelIngresoLayout.setVerticalGroup(
            PanelIngresoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelIngresoLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(PanelIngresoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(LabelArea)
                    .add(TipoCama, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(LabelTipoCama)
                    .add(LabelNumCama)
                    .add(Cama, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Area, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        LabelAlergias.setText("Alergias");

        LabelCaidas.setText("Riesgo de Caida");

        RiesgoCaida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verde", "Amarillo", "Rojo" }));

        RiesgoUlsera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verde", "Amarillo", "Rojo" }));

        LabelUlsera.setText("Riesgo de Ulsera");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar Tarjera");

        jScrollPane1.setViewportView(Alergias);

        Masculino.setText("Masculino");

        Femenino.setText("Femenino");

        org.jdesktop.layout.GroupLayout RegistrarPacienteLayout = new org.jdesktop.layout.GroupLayout(RegistrarPaciente);
        RegistrarPaciente.setLayout(RegistrarPacienteLayout);
        RegistrarPacienteLayout.setHorizontalGroup(
            RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, RegistrarPacienteLayout.createSequentialGroup()
                .add(52, 52, 52)
                .add(LabelTituloRegistro, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(38, 38, 38))
            .add(RegistrarPacienteLayout.createSequentialGroup()
                .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(RegistrarPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 429, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(RegistrarPacienteLayout.createSequentialGroup()
                        .add(9, 9, 9)
                        .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(LabelSexualidad)
                            .add(LabelNombre))
                        .add(22, 22, 22)
                        .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(RegistrarPacienteLayout.createSequentialGroup()
                                .add(Masculino)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(Femenino)
                                .add(12, 12, 12)
                                .add(LabelFolio)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(NumExpediente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(NombrePasiente))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(RegistrarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(RegistrarPacienteLayout.createSequentialGroup()
                        .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PanelNacimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(LabelAlergias))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(RegistrarPacienteLayout.createSequentialGroup()
                        .add(LabelCaidas)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(LabelUlsera)
                        .add(108, 108, 108))))
            .add(RegistrarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .add(RiesgoCaida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(RiesgoUlsera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(RegistrarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(RegistrarPacienteLayout.createSequentialGroup()
                        .add(PanelIngreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(RegistrarPacienteLayout.createSequentialGroup()
                        .add(Guardar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistrarPacienteLayout.setVerticalGroup(
            RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(RegistrarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .add(LabelTituloRegistro)
                .add(18, 18, 18)
                .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(NombrePasiente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(LabelNombre))
                .add(18, 18, 18)
                .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(LabelSexualidad)
                        .add(Masculino)
                        .add(Femenino))
                    .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(LabelFolio)
                        .add(NumExpediente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(PanelNacimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PanelIngreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(LabelAlergias)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(LabelCaidas)
                    .add(LabelUlsera))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(RiesgoCaida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(RiesgoUlsera, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(RegistrarPacienteLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Guardar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .add(jButton2))
                .add(14, 14, 14))
        );

        jTabbedPane1.addTab("tab1", RegistrarPaciente);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel12.setText("Pacientes");

        jButton1.setText("popup");

        jTextField1.setText("jTextField1");

        jLabel2.setText("Buscar");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(160, 160, 160)
                        .add(jButton1))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(33, 33, 33)
                        .add(jLabel2)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(67, 67, 67)
                                .add(jLabel12))
                            .add(jPanel4Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 260, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(122, 122, 122)
                        .add(jCalendar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel12)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(87, 87, 87)
                .add(jCalendar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 71, Short.MAX_VALUE)
                .add(jButton1)
                .add(72, 72, 72))
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /////////////////////////////////////////////////////////////////
    ////////////////////////Insertar Pasiente////////////////////////
    public void Insertar(){
        ConsultMysql consulta = new ConsultMysql();
        
       //////// Se crea la conexion a MySQL para acceder a la base dedatos
        try {
            consulta.ConsultMysql();
        } catch (InstantiationException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        ////////////////////////////////////
        Date date = FechaNacimiento.getDate();
        java.sql.Date Fechasql = new java.sql.Date(date.getTime());
        consulta.setInsertarPasiente(InfoPasiente,Fechasql);
    }
    
    
    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        int cont=0;
        if (Masculino.isSelected()) {
            sexo = "Masculino";
        }else if (Femenino.isSelected()) {
            sexo = "Femenino";
        }
        InfoPasiente.add(NombrePasiente.getText());
        InfoPasiente.add(NumExpediente.getText());
        InfoPasiente.add(sexo);
        InfoPasiente.add(Alergias.getText());
        
        InfoPasiente.add((String)Area.getSelectedItem());
        InfoPasiente.add((String)TipoCama.getSelectedItem());
        InfoPasiente.add((String)Cama.getSelectedItem());
        InfoPasiente.add((String)RiesgoCaida.getSelectedItem());
        InfoPasiente.add((String)RiesgoUlsera.getSelectedItem());
        for (int i = 0; i < InfoPasiente.size(); i++) {
            String campo = ""+InfoPasiente.get(i);
            if (!campo.equals("")) {
                cont++;
                                     
            }
        }
        if (FechaNacimiento.getDate() != null) {
            cont++;
            
        }
        
        if (cont==10) {
            cont = 0;
            ConfirmarNombre.setText(NombrePasiente.getText());
            ConfirmarSexo.setText(sexo);
            ConfirmarExpediente.setText(NumExpediente.getText());
            ConfirmarArea.setText((String)Area.getSelectedItem()+" cama "+(String)TipoCama.getSelectedItem()+" numero "+(String)Cama.getSelectedItem());
            ConfirmarAlergias.setText(Alergias.getText());
            ConfirmarRiesgoCaida.setText((String)RiesgoCaida.getSelectedItem());
            ConfirmarRiesgoUlsera.setText((String)RiesgoUlsera.getSelectedItem());
            jFrame1.show();
            jFrame1.setLocationRelativeTo(null);
        }else{
            cont=0;
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.Insertar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void NumExpedienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumExpedienteKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != evt.VK_BACK_SPACE) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_NumExpedienteKeyTyped

    private void RegistrarPacienteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_RegistrarPacienteComponentShown
        ConsultMysql consulta = new ConsultMysql();
        
       //////// Se crea la conexion a MySQL para acceder a la base dedatos
        try {
            consulta.ConsultMysql();
        } catch (InstantiationException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        ////////////////////////////////////
        
        ArrayList areas = new ArrayList();
        areas = consulta.getAreas();
        if (!areas.isEmpty()) {
            for (int i = 0; i < areas.size(); i++) {
                Area.addItem(""+areas.get(i));
            }
        }
    }//GEN-LAST:event_RegistrarPacienteComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nivel_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nivel_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nivel_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nivel_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nivel_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane Alergias;
    private javax.swing.JComboBox<String> Area;
    private javax.swing.ButtonGroup ButtonGroupSexualidad;
    private javax.swing.JComboBox<String> Cama;
    private javax.swing.JPanel Confirmar;
    private javax.swing.JEditorPane ConfirmarAlergias;
    private javax.swing.JLabel ConfirmarArea;
    private com.toedter.calendar.JYearChooser ConfirmarAño;
    private com.toedter.components.JSpinField ConfirmarDia;
    private javax.swing.JLabel ConfirmarExpediente;
    private com.toedter.calendar.JMonthChooser ConfirmarMes;
    private javax.swing.JLabel ConfirmarNombre;
    private javax.swing.JLabel ConfirmarRiesgoCaida;
    private javax.swing.JLabel ConfirmarRiesgoUlsera;
    private javax.swing.JLabel ConfirmarSexo;
    private com.toedter.calendar.JDateChooser FechaNacimiento;
    private javax.swing.JRadioButton Femenino;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel LabelAlergias;
    private javax.swing.JLabel LabelArea;
    private javax.swing.JLabel LabelCaidas;
    private javax.swing.JLabel LabelCaidas1;
    private javax.swing.JLabel LabelCaidas2;
    private javax.swing.JLabel LabelFolio;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNumCama;
    private javax.swing.JLabel LabelSexualidad;
    private javax.swing.JLabel LabelTipoCama;
    private javax.swing.JLabel LabelTituloRegistro;
    private javax.swing.JLabel LabelUlsera;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JTextField NombrePasiente;
    private javax.swing.JTextField NumExpediente;
    private javax.swing.JPanel PanelIngreso;
    private javax.swing.JPanel PanelNacimiento;
    private javax.swing.JPanel RegistrarPaciente;
    private javax.swing.JComboBox<String> RiesgoCaida;
    private javax.swing.JComboBox<String> RiesgoUlsera;
    private javax.swing.JComboBox<String> TipoCama;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private String sexo; 
    ArrayList InfoPasiente = new ArrayList();
}
